import {SCALE_KEYS,BODY_EDGES,BODY_NAMES,clone,applyFrame} from './pose-core.js?v=10';
import {FrameLoader,FramePresenter} from './frame-loader.js';
function startEditor(){
document.addEventListener('contextmenu',e=>e.preventDefault());
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');
let frames=[],operations=[],sourceDigest='',current=0,drag=null,playing=false,playbackGeneration=0,lastTick=0,history=[],sessionData=null,videoURL=null,initialEdits=null,handFixes=[],manualMode=false,pendingJoint=null,manualPreview=null,hoveredScale=null,dragMode='joint';
const completionDisabled=new Map();
const scales=Object.fromEntries(SCALE_KEYS.map(k=>[k,1]));
const labels={head_x:'头部宽度',head_y:'头部高度',neck:'脖子长度',shoulders:'肩宽',upper_arm:'上臂长度',lower_arm:'前臂长度',torso:'躯干长度',hips:'胯宽',upper_leg:'大腿长度',lower_leg:'小腿长度',hands:'手掌大小',feet:'脚部大小'};
const scaleRegions={head_x:[0,14,15,16,17],head_y:[0,14,15,16,17],neck:[1,0],shoulders:[2,1,5],upper_arm:[2,3,5,6],lower_arm:[3,4,6,7],torso:[1,8,11],hips:[8,11],upper_leg:[8,9,11,12],lower_leg:[9,10,12,13],hands:[4,7],feet:[10,13]};
const scaleHelp={head_x:'以鼻尖为中心调整头部和脸部宽度',head_y:'以鼻尖为中心调整头部和脸部高度，不改变脖子长度',neck:'胸肩交接点固定，移动整个头部和脸部',shoulders:'调整两肩间距，手臂随肩膀移动',upper_arm:'调整肩膀到手肘的长度，前臂和手掌跟随',lower_arm:'调整手肘到手腕的长度，手掌跟随',torso:'调整肩部到髋部的距离，双腿跟随',hips:'调整左右髋部间距，双腿跟随',upper_leg:'调整髋部到膝盖的长度，小腿和脚跟随',lower_leg:'调整膝盖到脚踝的长度，脚部跟随',hands:'以手腕为中心缩放手掌',feet:'以脚踝为中心缩放脚部'};
const colors=['#ff5555','#ffaa44','#ffee55','#99ee55','#44ee88','#55dddd','#55aaff','#aa77ff'];
const params=new URLSearchParams(location.search),token=params.get('session'),apiBase=params.get('api')||'/api/xiaozhuguang/pose/session/';
let frameRate=25;const rate=()=>Math.max(1,Math.min(240,Number(frameRate)||25));
const status=text=>$('status').textContent=text;
function scaleAt(frame=current,person=Number($('person').value)){const keys=operations.filter(op=>op.type==='scale'&&op.person===person&&Number.isInteger(op.frame)).sort((a,b)=>a.frame-b.frame);if(!keys.length)return Object.fromEntries(SCALE_KEYS.map(k=>[k,1]));let a=keys[0],b=keys.at(-1);if(frame<=a.frame)b=a;else if(frame>=b.frame)a=b;else for(let i=1;i<keys.length;i++)if(keys[i].frame>=frame){a=keys[i-1];b=keys[i];break;}const t=a===b?0:(frame-a.frame)/(b.frame-a.frame);return Object.fromEntries(SCALE_KEYS.map(k=>[k,(a.values?.[k]??1)+((b.values?.[k]??1)-(a.values?.[k]??1))*t]));}
function previewOp(){return scalesDirty?{type:'scale',frame:current,person:Number($('person').value),values:{...scales}}:null;}
function editFrame(index=current){return frames[index];}
function allOps(){const op=previewOp(),base=operations.filter(item=>!(op&&item.type==='scale'&&item.person===op.person&&item.frame===current));return [...handFixes,...base,...(op?[op]:[]),...(manualPreview?[manualPreview]:[]),...(drag?[drag.op]:[])];}
function remember(){history.push({operations:clone(operations),handFixes:clone(handFixes)});if(history.length>100)history.shift();}
let scalesDirty=false,scalePreviewFrame=0;
function updateScalePreview(key,input){const value=Number(input.value);if(scales[key]===value)return;scales[key]=value;scalesDirty=true;input.nextElementSibling.value=value.toFixed(2);if(!scalePreviewFrame)scalePreviewFrame=requestAnimationFrame(()=>{scalePreviewFrame=0;draw();});}
function resetPreview(){scalesDirty=false;const values=scaleAt();SCALE_KEYS.forEach(k=>scales[k]=values[k]);document.querySelectorAll('.slider').forEach(row=>{const key=row.dataset.key;row.querySelector('input').value=scales[key];row.querySelector('output').value=scales[key].toFixed(2);});draw();}
function commitScale(){if(!scalesDirty)return;remember();const person=Number($('person').value),at=operations.findIndex(op=>op.type==='scale'&&op.person===person&&op.frame===current);const op={type:'scale',frame:current,person,values:{...scales}};if(at>=0)operations[at]=op;else operations.push(op);scalesDirty=false;updateOperations();renderKeyframes();draw();status(`已在第 ${current+1} 帧记录比例关键帧`);}
function upsert(op){remember();const at=operations.findIndex(old=>old.type===op.type&&old.person===op.person&&old.frame===op.frame&&(!['joint','set_joint'].includes(op.type)||old.joint===op.joint));if(at>=0){if(['translate','joint'].includes(op.type)){op.dx+=(operations[at].dx||0);op.dy+=(operations[at].dy||0);}operations[at]=op;}else operations.push(op);updateOperations();renderKeyframes();draw();}
function renderKeyframes(){const track=$('keyframeTrack');track.replaceChildren();const keys=[...new Set(operations.map(op=>op.frame).filter(Number.isInteger))].sort((a,b)=>a-b);for(const frame of keys){const marker=document.createElement('button');marker.className='keyframe-marker';marker.disabled=manualMode;marker.style.left=`${frames.length>1?frame/(frames.length-1)*100:0}%`;marker.title=`第 ${frame+1} 帧关键帧`;marker.setAttribute('aria-label',marker.title);marker.onclick=()=>{pause();setFrame(frame);};track.append(marker);}}
function updateOperations(){renderKeyframes();}
function initialize(data){if(!Array.isArray(data)||!data.length)throw Error('骨骼数组为空');data.forEach(f=>{if(!Number.isFinite(f.canvas_width)||f.canvas_width<=0||!Number.isFinite(f.canvas_height)||f.canvas_height<=0||!Array.isArray(f.people))throw Error('骨骼帧格式无效');f.people.forEach(p=>{for(const [key,flat]of Object.entries(p)){if(key.endsWith('_keypoints_2d')&&(!Array.isArray(flat)||flat.length%3||flat.some(v=>!Number.isFinite(v))))throw Error('关节点格式无效');}if(p.pose_keypoints_2d?.length!==54)throw Error('需要 SDPOSE / OpenPose 18 身体关节');});});frames=clone(data);current=0;operations=[];handFixes=[{type:'swap_hands',person:-1}];finishManual();history=[];$('seek').max=frames.length-1;const count=Math.max(...frames.map(f=>f.people.length));$('person').replaceChildren();for(let i=-1;i<count;i++){const option=document.createElement('option');option.value=i;option.textContent=i===-1?'所有人物':`人物 ${i+1}`;$('person').append(option);}$('info').textContent=`${frames.length} 帧 · 最多 ${count} 人 · SDPOSE 全身骨骼`;resetPreview();updateOperations();resize();setFrame(0);}
function resize(){const frame=frames[current];if(!frame)return;const box=$('stage'),ratio=frame.canvas_width/frame.canvas_height,w=Math.min(box.clientWidth,box.clientHeight*ratio),h=w/ratio,dpr=devicePixelRatio||1;canvas.style.width=w+'px';canvas.style.height=h+'px';canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
function drawFrame(frame){const w=parseFloat(canvas.style.width),h=parseFloat(canvas.style.height),sx=w/frame.canvas_width,sy=h/frame.canvas_height,selected=Number($('person').value),region=scaleRegions[hoveredScale]??[],focused=!manualMode&&region.length>0;ctx.save();ctx.filter=`saturate(${Number($('saturation').value)})`;ctx.lineWidth=Number($('lineWidth').value);
 function group(flat,edges,color,radius,active){const points=[];for(let i=0;i<flat.length;i+=3)points.push([flat[i]*sx,flat[i+1]*sy,flat[i+2]]);edges.forEach(([a,b],n)=>{if(!points[a]||!points[b]||points[a][2]<=.3||points[b][2]<=.3)return;ctx.strokeStyle=focused&&!active(a,b)?'#707780':color||colors[n%colors.length];ctx.beginPath();ctx.moveTo(...points[a].slice(0,2));ctx.lineTo(...points[b].slice(0,2));ctx.stroke();});points.forEach(([x,y,score],i)=>{if(score<=.3)return;ctx.fillStyle=focused&&!active(i)?'#707780':color||'#fff';ctx.beginPath();ctx.arc(x,y,radius,0,Math.PI*2);ctx.fill();});}
 frame.people.forEach((p,person)=>{const matches=selected===-1||selected===person,bodyActive=(a,b)=>matches&&region.includes(a)&&(b===undefined||region.includes(b)),headActive=()=>matches&&(region.includes(0)||['head_x','head_y','neck'].includes(hoveredScale));group(p.pose_keypoints_2d,BODY_EDGES,null,4,bodyActive);group(p.face_keypoints_2d??[],[],'#fff',1.3,headActive);const handEdges=[];for(const root of [1,5,9,13,17])for(let j=0;j<4;j++)handEdges.push([j===0?0:root+j-1,root+j]);group(p.hand_left_keypoints_2d??[],handEdges,'#66dddd',2,()=>matches&&(hoveredScale==='hands'));group(p.hand_right_keypoints_2d??[],handEdges,'#ffbb66',2,()=>matches&&(hoveredScale==='hands'));group(p.foot_keypoints_2d??[],[[0,1],[0,2],[3,4],[3,5]],'#a8ec77',2,()=>matches&&hoveredScale==='feet');});
 ctx.restore();const drawn=allOps().filter(op=>op.type==='set_joint'&&current>=(op.start??0)&&current<=(op.end??Infinity));ctx.save();ctx.font='600 11px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';frame.people.forEach((p,person)=>{if(selected!==-1&&selected!==person)return;const body=p.pose_keypoints_2d;for(let joint=0;joint<18;joint++){if(body[joint*3+2]<=.3)continue;const lx=body[joint*3]*sx+13,ly=body[joint*3+1]*sy-12;ctx.fillStyle='#101820dd';ctx.beginPath();ctx.arc(lx,ly,9,0,Math.PI*2);ctx.fill();if(drawn.some(op=>op.joint===joint&&(op.person===person||op.person===-1))){ctx.strokeStyle=focused&&!region.includes(joint)?'#707780':'#ff6666';ctx.lineWidth=2;ctx.stroke();}ctx.fillStyle=focused&&!region.includes(joint)?'#707780':'#a7ed7c';ctx.fillText(String(joint+1),lx,ly);}});ctx.restore();
}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);if(!frames.length)return;const displayed=drag?applyFrame(drag.baseFrame,current,[drag.op],frames.length):applyFrame(editFrame(),current,allOps(),frames.length);drawFrame(displayed);if(manualMode){const person=Number($('person').value),body=displayed.people[person]?.pose_keypoints_2d,drawn=allOps().filter(op=>op.type==='set_joint'&&(op.person===person||op.person===-1)&&current>=(op.start??0)&&current<=(op.end??Infinity));document.querySelectorAll('#poseMap .pose-joint').forEach(item=>{const joint=Number(item.dataset.joint),missing=!(body?.[joint*3+2]>.3);item.classList.toggle('missing',missing);item.classList.toggle('drawn',!missing&&drawn.some(op=>op.joint===joint));item.querySelector('title').textContent=`${BODY_NAMES[joint]}${missing?'（缺失）':''}`;});}}
const frameLoader=new FrameLoader(index=>new Promise((resolve,reject)=>{
 const img=new Image(),timer=setTimeout(()=>{img.onload=img.onerror=null;reject(Error('视频帧加载超时，请检查 ComfyUI 是否仍在运行'));},15000);
 img.onload=()=>{clearTimeout(timer);resolve(img);};img.onerror=()=>{clearTimeout(timer);reject(Error('视频帧加载失败，请重新执行编辑节点刷新预览缓存'));};
 img.src=apiBase+encodeURIComponent(token)+'/image/'+index;
}));
function commitFrame(index,image=null){
 current=index;$('seek').value=current;$('frameLabel').textContent=`第 ${current+1} / ${frames.length} 帧`;resetPreview();
 const showLocal=Boolean(videoURL),showOriginal=!showLocal&&$('showBackground').checked;$('video').style.visibility=showLocal?'visible':'hidden';
 if(image&&showOriginal){const previous=$('background');image.id='background';image.alt='原视频帧';image.hidden=false;if(previous!==image)previous.replaceWith(image);}else $('background').hidden=true;
 if(videoURL)$('video').currentTime=current/rate();resize();
}
const presenter=new FramePresenter(frameLoader,commitFrame,(error,index)=>{pause();$('seek').value=current;status(`第 ${index+1} 帧：${error.message}`);});
async function setFrame(f){
 if(!frames.length)return false;const target=Math.max(0,Math.min(frames.length-1,Math.round(f)));
 if(sessionData?.has_images&&!videoURL&&$('showBackground').checked){
  // Update the pose and frame counter synchronously while the matching video image loads.
  commitFrame(target);
  const shown=await presenter.show(target);
  if(shown)frameLoader.prefetch([target+1,target+2].filter(i=>i<frames.length));
  return shown;
 }
 presenter.cancel();commitFrame(target);return true;
}
function background(){if($('showBackground').checked&&videoURL){URL.revokeObjectURL(videoURL);videoURL=null;$('video').pause();$('video').removeAttribute('src');$('video').load();status('已切换回节点原视频');}return setFrame(current);}
function pause(){playing=false;playbackGeneration++;presenter.cancel();$('play').textContent='▶ 播放';$('video').pause();}
async function tick(time){
 if(!playing)return;const generation=playbackGeneration,interval=1000/rate();
 if(time-lastTick>=interval){
  lastTick=time;if(current>=frames.length-1){pause();return;}
  const shown=await setFrame(current+1);
  if(!playing||generation!==playbackGeneration)return;
  if(!shown){pause();return;}
 }
 if(playing)requestAnimationFrame(tick);
}
const svgNS='http://www.w3.org/2000/svg',poseMap=$('poseMap'),posePoints=[[125,42],[125,88],[91,95],[58,132],[43,170],[159,95],[192,132],[207,170],[105,174],[99,240],[94,310],[145,174],[151,240],[156,310],[116,37],[134,37],[103,43],[147,43]];
for(const [a,b] of BODY_EDGES){const line=document.createElementNS(svgNS,'line');line.setAttribute('x1',posePoints[a][0]);line.setAttribute('y1',posePoints[a][1]);line.setAttribute('x2',posePoints[b][0]);line.setAttribute('y2',posePoints[b][1]);line.setAttribute('class','pose-bone');poseMap.append(line);}
function choosePoseJoint(index){pause();manualPreview=null;pendingJoint=index;const person=Number($('person').value),frame=applyFrame(editFrame(),current,allOps(),frames.length),body=frame.people[person]?.pose_keypoints_2d;if(body&&!(body[index*3+2]>.3)){const neighbors=BODY_EDGES.flatMap(([a,b])=>a===index?[b]:b===index?[a]:[]),anchor=neighbors.find(j=>body[j*3+2]>.3)??Array.from({length:18},(_,j)=>j).find(j=>body[j*3+2]>.3);let x=frame.canvas_width/2,y=frame.canvas_height/2;if(anchor!==undefined){let scale=frame.canvas_height/350;if(body[5]>.3&&body[26]>.3){scale=Math.hypot(body[3]-body[24],body[4]-body[25])/Math.hypot(posePoints[1][0]-posePoints[8][0],posePoints[1][1]-posePoints[8][1]);}x=body[anchor*3]+(posePoints[index][0]-posePoints[anchor][0])*scale;y=body[anchor*3+1]+(posePoints[index][1]-posePoints[anchor][1])*scale;}upsert({type:'set_joint',frame:current,person,joint:index,x:x/frame.canvas_width,y:y/frame.canvas_height});}draw();poseMap.querySelectorAll('.pose-joint').forEach(item=>item.classList.toggle('selected',Number(item.dataset.joint)===index));$('poseSelection').textContent=`${index+1}. ${BODY_NAMES[index]}：在工作区按住拖动绘制`; status(`已选择${BODY_NAMES[index]}，请在工作区按住拖动绘制。按 Esc 可取消。`);}
BODY_NAMES.forEach((name,index)=>{const group=document.createElementNS(svgNS,'g');group.setAttribute('class','pose-joint');group.setAttribute('tabindex','0');group.setAttribute('role','button');group.setAttribute('aria-label',name);group.dataset.joint=index;const title=document.createElementNS(svgNS,'title');title.textContent=name;const circle=document.createElementNS(svgNS,'circle');circle.setAttribute('cx',posePoints[index][0]);circle.setAttribute('cy',posePoints[index][1]);circle.setAttribute('r',index>13?8:11);const label=document.createElementNS(svgNS,'text');label.setAttribute('x',posePoints[index][0]);label.setAttribute('y',posePoints[index][1]+3);label.textContent=String(index+1);group.append(title,circle,label);group.onclick=()=>choosePoseJoint(index);group.oncontextmenu=e=>{e.preventDefault();deletePoseJoint(index);};group.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choosePoseJoint(index);}};poseMap.append(group);});
function setPoseMode(complete){if(complete&&!manualMode){document.querySelectorAll('button,input,select').forEach(control=>{if(control.id==='adjustPose')return;completionDisabled.set(control,control.disabled);control.disabled=true;});}else if(!complete&&manualMode){completionDisabled.forEach((disabled,control)=>control.disabled=disabled);completionDisabled.clear();}manualMode=complete;$('adjustPose').textContent=complete?'确认补全':'姿势调节';$('adjustPose').classList.toggle('confirm-completion',complete);pendingJoint=null;manualPreview=null;hoveredScale=null;$('posePicker').hidden=!complete;$('adjustPanel').hidden=complete;for(const [id,active] of [['adjustPose',!complete],['manualPose',complete]]){$(id).classList.toggle('active',active);$(id).setAttribute('aria-pressed',String(active));}poseMap.querySelectorAll('.pose-joint').forEach(item=>item.classList.remove('selected'));$('poseSelection').textContent='左键编号绘制，右键编号删除。';renderKeyframes();draw();}
function finishManual(){setPoseMode(false);}
$('adjustPose').onclick=finishManual;
function deletePoseJoint(joint){if(!manualMode||!frames[current]?.people.length)return;pause();manualPreview=null;const person=Number($('person').value),frame=applyFrame(editFrame(),current,allOps(),frames.length),body=frame.people[person].pose_keypoints_2d;upsert({type:'set_joint',frame:current,person,joint,x:body[joint*3]/frame.canvas_width,y:body[joint*3+1]/frame.canvas_height,deleted:true});status(`已删除第 ${current+1} 帧的${BODY_NAMES[joint]}，可撤销或重新绘制。`);}
$('manualPose').onclick=()=>{pause();if(scalesDirty)commitScale();if(!frames[current]?.people.length){status('当前帧没有可补画的人物');return;}if(Number($('person').value)<0){$('person').value='0';$('person').dispatchEvent(new Event('change'));}setPoseMode(true);};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&manualMode)finishManual();});
SCALE_KEYS.forEach(key=>{const row=document.createElement('div');row.className='slider';row.dataset.key=key;row.onpointerenter=()=>{hoveredScale=key;status(`${labels[key]}：${scaleHelp[key]}`);draw();};row.onfocusin=()=>{hoveredScale=key;status(`${labels[key]}：${scaleHelp[key]}`);draw();};row.innerHTML=`<span>${labels[key]}</span><input type="range" min="0.1" max="3" step="0.01" value="1"><output>1.00</output><button type="button" class="slider-reset" title="重置为 1" aria-label="${labels[key]}重置为 1">↺</button>`;const input=row.querySelector('input');input.addEventListener('input',()=>updateScalePreview(key,input));input.addEventListener('pointermove',e=>{if(e.buttons)updateScalePreview(key,input);});input.onchange=commitScale;row.querySelector('.slider-reset').onclick=()=>{if(scales[key]===1)return;scales[key]=1;input.value=1;row.querySelector('output').value='1.00';scalesDirty=true;commitScale();};$('sliders').append(row);});
$('sliders').onpointerleave=()=>{hoveredScale=null;draw();};$('sliders').onfocusout=e=>{if(!$('sliders').contains(e.relatedTarget)&&!$('sliders').matches(':hover')){hoveredScale=null;draw();}};
 document.querySelectorAll('#dragModes button').forEach(button=>{button.onclick=()=>{if(manualMode)finishManual();dragMode=button.dataset.mode;document.querySelectorAll('#dragModes button').forEach(item=>{const active=item.dataset.mode===dragMode;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active));});};});
$('person').onchange=()=>{resetPreview();draw();};$('lineWidth').oninput=draw;$('saturation').oninput=draw;$('showBackground').onchange=background;
$('seek').oninput=e=>{if(scalesDirty)commitScale();pause();setFrame(Number(e.target.value));};$('prev').onclick=()=>{if(scalesDirty)commitScale();pause();setFrame(current-1);};$('next').onclick=()=>{if(scalesDirty)commitScale();pause();setFrame(current+1);};$('play').onclick=()=>{if(!frames.length)return;if(scalesDirty)commitScale();if(playing)return pause();playing=true;const generation=++playbackGeneration;if(current===frames.length-1){setFrame(0).then(shown=>{if(playing&&shown&&generation===playbackGeneration){lastTick=performance.now();requestAnimationFrame(tick);}});$('play').textContent='Ⅱ 暂停';return;}lastTick=performance.now();$('play').textContent='Ⅱ 暂停';requestAnimationFrame(tick);};
$('undo').onclick=()=>{if(!history.length)return;const state=history.pop();operations=state.operations;handFixes=state.handFixes;scalesDirty=false;resetPreview();updateOperations();draw();status('已撤销');};$('reset').onclick=()=>{remember();operations=[];handFixes=[{type:'swap_hands',person:-1}];scalesDirty=false;resetPreview();updateOperations();draw();status('已清除全部调整');};
canvas.onpointerdown=e=>{if(!frames.length)return;try{pause();if(scalesDirty)commitScale();const box=canvas.getBoundingClientRect(),x=(e.clientX-box.left)/box.width,y=(e.clientY-box.top)/box.height;if(manualMode){if(pendingJoint===null){status('请先在右侧选择要补全的关节编号');return;}manualPreview=null;drag={op:{type:'set_joint',frame:current,person:Number($('person').value),joint:pendingJoint,x,y},baseFrame:applyFrame(editFrame(),current,allOps(),frames.length)};canvas.setPointerCapture(e.pointerId);draw();return;}const op={type:dragMode==='move'?'translate':'joint',frame:current,person:Number($('person').value),dx:0,dy:0},baseFrame=applyFrame(editFrame(),current,allOps(),frames.length);if(op.type==='joint'){let best=null,dist=18;baseFrame.people.forEach((p,person)=>{if(op.person!==-1&&person!==op.person)return;const flat=p.pose_keypoints_2d;for(let j=0;j<18;j++){if(flat[j*3+2]<=.3)continue;const d=Math.hypot((flat[j*3]/baseFrame.canvas_width-x)*box.width,(flat[j*3+1]/baseFrame.canvas_height-y)*box.height);if(d<dist){dist=d;best={joint:j,person};}}});if(!best)return;op.joint=best.joint;op.person=best.person;}drag={x,y,op,baseFrame};canvas.setPointerCapture(e.pointerId);}catch(err){status(err.message);}};
canvas.onpointermove=e=>{const box=canvas.getBoundingClientRect(),x=(e.clientX-box.left)/box.width,y=(e.clientY-box.top)/box.height;if(drag){if(drag.op.type==='set_joint'){drag.op.x=x;drag.op.y=y;}else{drag.op.dx=x-drag.x;drag.op.dy=y-drag.y;}draw();}else if(manualMode&&pendingJoint!==null&&frames[current]?.people.length){manualPreview={type:'set_joint',frame:current,person:Number($('person').value),joint:pendingJoint,x,y};draw();}};canvas.onpointerleave=()=>{if(!drag){manualPreview=null;draw();}};
function endDrag(){if(!drag)return;const op=drag.op;drag=null;if(op.type==='set_joint'||Math.abs(op.dx)+Math.abs(op.dy)>1e-8){upsert(op);status(`已在第 ${current+1} 帧创建关键帧`);}draw();}canvas.onpointerup=endDrag;canvas.onpointercancel=()=>{drag=null;manualPreview=null;draw();};
$('save').onclick=()=>{try{if(!token||!sessionData)throw Error('请从 ComfyUI 节点打开编辑器');commitScale();parent.postMessage({type:'comfyui-pose:save',fps:rate(),edits:{version:1,source_digest:sourceDigest,operations,hand_fixes:handFixes}},location.origin);}catch(e){status(e.message);}};$('close').onclick=()=>{pause();parent.postMessage({type:'comfyui-pose:close'},location.origin);};
$('loadVideo').onclick=()=>$('videoFile').click();$('videoFile').onchange=e=>{const file=e.target.files[0];if(!file)return;if(videoURL)URL.revokeObjectURL(videoURL);pause();$('showBackground').checked=false;videoURL=URL.createObjectURL(file);$('video').src=videoURL;$('background').hidden=true;setFrame(current);status('已切换到本地参考视频；勾选“原视频”可切回节点视频');};
$('loadJSON').onclick=()=>$('jsonFile').click();$('jsonFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(token)throw Error('节点编辑模式不能替换源数据；需要更换源数据时请修改工作流输入并重新执行');pause();sourceDigest='';initialize(JSON.parse(await file.text()));status('骨骼 JSON 已导入');}catch(err){status(err.message);}};
$('demo').onclick=()=>{if(token)return status('节点编辑模式请使用输入骨骼');initialize(Array.from({length:80},(_,f)=>{const p=[[.5,.2],[.5,.3],[.4,.3],[.34,.44],[.3,.56],[.6,.3],[.66,.44],[.7,.56],[.45,.55],[.44,.72],[.42,.9],[.55,.55],[.56,.72],[.58,.9],[.48,.18],[.52,.18],[.46,.2],[.54,.2]];return {canvas_width:640,canvas_height:480,people:[{pose_keypoints_2d:p.flatMap(([x,y],i)=>[(x+(i===4?.05*Math.sin(f/8):0))*640,y*480,1]),face_keypoints_2d:[],hand_left_keypoints_2d:[],hand_right_keypoints_2d:[],foot_keypoints_2d:[]}]};}));status('80 帧关键帧演示：在不同帧调整动作，检查中间帧的过渡');};
function restoreEdits(value){if(!frames.length)return;try{const data=typeof value==='string'?JSON.parse(value):value;if(!data||data.version!==1||!Array.isArray(data.operations))throw Error('编辑项目格式无效');if(data.source_digest&&data.source_digest!==sourceDigest){status('源骨骼已改变，旧调整未加载；保存新调整可替换旧项目');return;}operations=clone(data.operations).filter(op=>!['complete_pose','swap_hands','repair_hands'].includes(op.type));handFixes=[{type:'swap_hands',person:-1},...(Array.isArray(data.hand_fixes)?clone(data.hand_fixes).filter(op=>op.type==='swap_arms'):[])];const groups=new Map(),kept=[];for(const op of operations){if(op.type==='swap_arms'&&!Number.isInteger(op.frame)){if(!handFixes.some(old=>old.type===op.type&&(old.person??-1)===(op.person??-1)))handFixes.push(op);}else if(Number.isInteger(op.frame)&&op.type==='swap_arms'){const key=`${op.type}|${op.person??-1}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(op);}else kept.push(op);}for(const events of groups.values()){const first=events[0],shouldKeep=events.length%2===1;if(shouldKeep)kept.push({type:first.type,person:first.person??-1});}operations=kept;updateOperations();draw();}catch(e){status(e.message);}}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent||e.data?.type!=='comfyui-pose:init')return;initialEdits=e.data.edits;if(frames.length)restoreEdits(initialEdits);});
if(token){$('demo').hidden=true;$('loadJSON').hidden=true;fetch(apiBase+encodeURIComponent(token)).then(async r=>{if(!r.ok)throw Error(await r.text());return r.json();}).then(data=>{sessionData=data;sourceDigest=data.source_digest;frameRate=data.fps;initialize(data.frames);if(initialEdits!==null)restoreEdits(initialEdits);status(`已加载 ${frames.length} 帧，可批量修改；保存后重新执行节点`);}).catch(e=>status(e.message));}
parent.postMessage({type:'comfyui-pose:ready'},location.origin);
new ResizeObserver(resize).observe($('stage'));
window.addEventListener('pagehide',()=>{pause();if(videoURL)URL.revokeObjectURL(videoURL);});

}
if(document.body?.dataset.poseEditor === "true") startEditor();
